[package]
name = "orange-nylon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.9.19"
serde = { version = "1", features = ["derive"] }
log = "0.4"
markdown = "1.0.0-alpha.7"